services:
  - type: web
    name: bandhan-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/prthamesh-pr/Bandhan.git
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: BACKEND_HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
